- shell:
    - sudo apt-get update
    - sudo apt-get install -y binutils
                              ccache
                              clang
                              clang-format
                              clang-tidy
                              clangd
                              cmake
                              fzf
                              git-crypt
                              git-extras
                              ncal
                              net-tools
                              swaks
                              tig
                              universal-ctags
                              yamllint
                              zeal
    - sudo snap install --classic code
    - python3 -m pip install pipx
    - ./install-google-chrome.sh
    - ./install-jfrog-cli.sh
