- shell:
    - sudo apt-get update
    - sudo apt-get install -y zeal
    - sudo apt-get install -y ncal
    - sudo apt-get install -y swaks
    - sudo snap install --classic code
    - python3 -m pip install pipx
    - ./install-google-chrome.sh
