---
- shell:
    - sudo apt-get update
    - sudo apt-get install -y binutils
                              ccache
                              clang-15
                              clang-format-15
                              clang-tidy-15
                              clangd-15
                              cmake
                              datamash
                              fzf
                              git-crypt
                              git-extras
                              git-lfs
                              ncal
                              net-tools
                              python-is-python3
                              swaks
                              tig
                              universal-ctags
                              yamllint
                              zeal
    - sudo update-alternatives --install /usr/bin/clang clang
                                         /usr/bin/clang-15 100
    - sudo update-alternatives --install /usr/bin/clang-format clang-format
                                         /usr/bin/clang-format-15 100
    - sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy
                                         /usr/bin/clang-tidy-15 100
    - sudo update-alternatives --install /usr/bin/clangd clangd
                                         /usr/bin/clangd-15 100
    - sudo snap install --classic code
    - sudo snap install --classic nvim
    - python3 -m pip install pynvim
    - python3 -m pip install pipx
    - pipx install conan
    - ./install-google-chrome.sh
    - ./install-jfrog-cli.sh
