- shell:
    - sudo apt-get update
    - sudo apt-get install -y clang-15
                              clangd-15
                              binutils
                              ncal
                              swaks
                              tig
                              zeal
    - sudo snap install --classic code
    - python3 -m pip install pipx
    - ./install-google-chrome.sh
