- shell:
    - sudo apt-get update
    - sudo apt-get install -y clangd
                              ncal
                              swaks
                              tig
                              zeal
    - sudo snap install --classic code
    - python3 -m pip install pipx
    - ./install-google-chrome.sh
