---
default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: 193cd7d27cd571f79358af09a8fb8997e54f8fff  # frozen: v2.3.0
    hooks:
      - id: codespell
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff  # frozen: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--norc"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: a3498aba5e94c9f7c4acb529b5e7eb6df65fd053  # frozen: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [Nonepre-pushNone]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: a30f0d816e5062a67d87c8de753cfe499672b959  # frozen: v1.5.5
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 1a92c0953500d402fc49ceb67ad7fbf7cabad38a  # frozen: 3.0.3
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 09cbf7c4e29373d4d4f15c9d17ddfbcd2e962955  # frozen: v3.9.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: aa1acdb72677dfbc5f507d2dfd45d8380bbcc2e0  # frozen: 0.29.3
    hooks:
      - id: check-github-workflows
      - id: check-renovate


ci:
  autoupdate_schedule: quarterly
