---
default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: 193cd7d27cd571f79358af09a8fb8997e54f8fff  # frozen: v2.3.0
    hooks:
      - id: codespell
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff  # frozen: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--norc"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: e9aa5d979ea6fd14dcf59c6bd3836bef17d386c1  # frozen: v3.27.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: a30f0d816e5062a67d87c8de753cfe499672b959  # frozen: v1.5.5
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2b74735540f79457a50369e5c17a2c35d52c3298  # frozen: 2.7.3
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: f9a49c0c4a9a57b1b094b5fd69b6c375cc957400  # frozen: v3.8.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 96ee1570b119e6337aafcc2f299bb0d902b68328  # frozen: 0.28.6
    hooks:
      - id: check-github-workflows
      - id: check-renovate


ci:
  autoupdate_schedule: quarterly
