---
default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482  # frozen: v2.2.6
    hooks:
      - id: codespell
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff  # frozen: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--norc"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 669080c8c180a1f81bc3f0666b0d49fb71ab6dde  # frozen: v3.21.3
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: a30f0d816e5062a67d87c8de753cfe499672b959  # frozen: v1.5.5
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2b74735540f79457a50369e5c17a2c35d52c3298  # frozen: 2.7.3
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: f9a49c0c4a9a57b1b094b5fd69b6c375cc957400  # frozen: v3.8.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: b3444eca522835c46db56fbf6cdd788d8e21217d  # frozen: 0.28.1
    hooks:
      - id: check-github-workflows
      - id: check-renovate


ci:
  autoupdate_schedule: quarterly
